# Generated by Django 3.0.2 on 2020-02-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='', max_length=1000)),
                ('speaker', models.CharField(default='', max_length=200)),
                ('place', models.CharField(choices=[('012', 'Main Building. First Floor: Classroom 12'), ('013', 'Main Building. First Floor: Classroom 13'), ('Mag', 'Main Building. Second Floor: Classroom '), ('022', 'Main Building. Second Floor: Classroom 22'), ('023', 'Main Building. Second Floor: Classroom 23'), ('024', 'Main Building. Second Floor: Classroom 24'), ('025', 'Main Building. Second Floor: Classroom 25'), ('026', 'Main Building. Second Floor: Classroom 26'), ('029', 'Main Building. Second Floor: Classroom 29'), ('030', 'Main Building. Third Floor: Classroom 30'), ('031', 'Main Building. Third Floor: Classroom 31'), ('032', 'Main Building. Third Floor: Classroom 32'), ('033', 'Main Building. Third Floor: Classroom 33'), ('104', 'Annex Building. Ground Floor: Classroom 104'), ('105', 'Annex Building. Ground Floor: Classroom 105'), ('110', 'Annex Building. First Floor: Classroom 110'), ('111', 'Annex Building. First Floor: Classroom 111'), ('117', 'Annex Building. First Floor: Classroom 117'), ('120', 'Annex Building. Second Floor: Classroom 120'), ('121', 'Annex Building. Second Floor: Classroom 121'), ('133', 'Annex Building. Third Floor: Classroom 133'), ('140', 'Annex Building. Forth Floor: Classroom 140'), ('152', 'Annex Building. Fifth Floor: Classroom 152')], default='012', max_length=100)),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
