# Generated by Django 3.0.2 on 2020-02-08 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ITBAEvent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=200)),
                ('last_name', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(default='', max_length=200)),
                ('title', models.CharField(default='', max_length=200)),
                ('speaker', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='registered',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ITBAEvent.participant'),
        ),
    ]
