# Generated by Django 3.0.2 on 2020-02-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ITBAEvent', '0002_auto_20200208_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='registered',
        ),
        migrations.AddField(
            model_name='event',
            name='registered',
            field=models.ManyToManyField(to='ITBAEvent.participant'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='company',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='participant',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
